services:
  api:
    image: ${ECR_REPOSITORY_URL}:latest
    container_name: comment-api
    ports:
      - "8000:8000"
    env_file:
      - ../.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 3s
      retries: 5
    pull_policy: always
    restart: unless-stopped

  ui:
    image: ${ECR_REPOSITORY_URL}:latest
    container_name: comment-ui
    command: streamlit run src/ui/app.py --server.port=8501 --server.address=0.0.0.0
    ports:
      - "8501:8501"
    env_file:
      - ../.env
    environment:
      - DOCKER_ENV=true
    depends_on:
      api:
        condition: service_healthy
    pull_policy: always
    restart: unless-stopped
