services:
  api:
    container_name: comment-api
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: mlops-comment-api:latest
    ports:
      - "8000:8000"
    volumes:
      - ../src:/app/src
      - ../data:/app/data
    env_file:
      - ../.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 3s
      retries: 5
      start_period: 0s

  
  ui:
    container_name: comment-ui
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: mlops-comment-ui:latest
    command: streamlit run src/ui/app.py --server.port=8501 --server.address=0.0.0.0
    ports:
      - "8501:8501"
    volumes:
      - ../src:/app/src
    env_file:
      - ../.env
    environment:
      - DOCKER_ENV=true
    depends_on:
      api:
        condition: service_healthy
